### ISSUE TITLE
TODO: Animations

### ISSUE THREAD

**Issue by ishaankolluri** [ishaankolluri/ThinkingAboutYou#4]
- [ ] Unmounting Components deserves something more.
- [ ] Opacity Change on load screens
- [ ] Custom modal popup?
